"""
Django settings for aurora project.

Generated by 'django-admin startproject' using Django 4.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = config('SECRET_KEY')
DEBUG = config('DEBUG', default=False, cast=bool)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='127.0.0.1', cast=Csv())

# Orígenes de confianza para CSRF (necesario en HTTPS con dominio propio).
# Ej: https://sruedadev.com,https://www.sruedadev.com
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=Csv())

# Producción detrás de Apache (reverse proxy) con TLS.
# Apache debe reenviar la cabecera X-Forwarded-Proto=https (mod_headers).
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # La redirección a HTTPS la hace Apache/Certbot; se deja opcional por env.
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=False, cast=bool)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'landing',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'aurora.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'aurora.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

_DB_ENGINE = config('DB_ENGINE', default='django.db.backends.sqlite3')

DATABASES = {
    'default': {
        'ENGINE':   _DB_ENGINE,
        'NAME':     config('DB_NAME',     default=str(BASE_DIR / 'db.sqlite3')),
        'USER':     config('DB_USER',     default=''),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST':     config('DB_HOST',     default=''),
        'PORT':     config('DB_PORT',     default='5432'),
        # sslmode solo aplica a PostgreSQL; con SQLite provoca un error.
        'OPTIONS': {'sslmode': 'require'} if 'postgresql' in _DB_ENGINE else {},
    }
}

# n8n — Webhook del asistente "Aurorita"
# Test:  .../webhook-test/aura-web  (solo responde al pulsar "Listen for test event" en n8n)
# Prod:  .../webhook/aura-web
N8N_WEBHOOK_URL = config(
    'N8N_WEBHOOK_URL',
    default='https://sruedagoat.app.n8n.cloud/webhook-test/aura-web',
)
# Timeout (segundos) para la llamada saliente a n8n
N8N_TIMEOUT = config('N8N_TIMEOUT', default=30, cast=int)

# Supabase API
SUPABASE_URL              = config('SUPABASE_URL',              default='')
SUPABASE_PUBLISHABLE_KEY  = config('SUPABASE_PUBLISHABLE_KEY',  default='')
SUPABASE_SECRET_KEY       = config('SUPABASE_SECRET_KEY',       default='')
SUPABASE_JWKS_URL         = config('SUPABASE_JWKS_URL',         default='')


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'

# Directorio raíz para imágenes y otros assets no pertenecientes a ninguna app
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Carpeta donde `collectstatic` reúne TODO lo estático para que Apache lo sirva.
# En producción apuntar a /var/www/html/static via la variable STATIC_ROOT.
STATIC_ROOT = config('STATIC_ROOT', default=str(BASE_DIR / 'staticfiles'))

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
